export class EffectEvent
{
	public static EV_PRIMARY_EFFECT_FINISHED = "EV_PRIMARY_EFFECT_FINISHED";
	public static EV_SECONDARY_EFFECT_FINISHED = "EV_SECONDARY_EFFECT_FINISHED";
	public static EV_TAKE_DAMAGE = "EV_TAKE_DAMAGE";
	public static EV_LOSE_MANA = "EV_LOSE_MANA";
	public static EV_GAIN_MANA = "EV_GAIN_MANA";
	public static EV_HEAL = "EV_HEAL";
	public static EV_TAKE_PENETRATE_DAMAGE = "EV_TAKE_PENETRATE_DAMAGE";
	public static EV_GET_SHIELD = "EV_GET_SHIELD";
	public static EV_GET_ABILITY_TEMPO = "EV_GET_ABILITY_TEMPO";

	public static EV_FIELD_TRANSFORM = "EV_FIELD_TRANSFORM";
	public static EV_FIELD_PARALYZE = "EV_FIELD_PARALYZE";
	public static EV_FIELD_STUN = "EV_FIELD_STUN";
	public static EV_FIELD_POISON = "EV_FIELD_POISON";

	public static EV_FREEZE_TABLE = "EV_FREEZE_TABLE";

	public static EV_POISON_DAMAGE = "EV_POISON_DAMAGE";
}
