export class TableEvent
{
	public static EV_START_SWAP = "EV_START_SWAP";
	public static EV_START_CASCADE = "EV_START_CASCADE";
	public static EV_FINISHED_CASCADE = "EV_FINISHED_CASCADE";
	public static EV_FINISHED_CASCADE_CHECK_POISONS = "EV_FINISHED_CASCADE_CHECK_POISONS";

	public static EV_FIELDS_PARALYZED = "EV_FIELDS_PARALYZED";
	public static EV_FIELDS_REMOVED = "EV_FIELDS_REMOVED";
	public static EV_NEW_FIELDS_CREATED = "EV_NEW_FIELDS_CREATED";
}
